//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace s1114760HW4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        public int Id { get; set; }
        public string 名稱 { get; set; }
        public string 尺寸 { get; set; }
        public string 顏色 { get; set; }
        public string 現貨 { get; set; }
    }
}
